// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0E774u1ZM-opEqpxt6kIY0CtKjwznY9Q',
    appId: '1:1013910398731:web:3f359e10e01c2d2993e40e',
    messagingSenderId: '1013910398731',
    projectId: 'detailing-xperts',
    authDomain: 'detailing-xperts.firebaseapp.com',
    storageBucket: 'detailing-xperts.appspot.com',
    measurementId: 'G-PVY56EQEVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYGsXtDeTBrMx8KnDdW8ZDEgqjyOGLvAw',
    appId: '1:1013910398731:android:2af50f2c433798ba93e40e',
    messagingSenderId: '1013910398731',
    projectId: 'detailing-xperts',
    storageBucket: 'detailing-xperts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBm5aeZ2o36Sdtyv8oL7o2LQffo-5B9MQ',
    appId: '1:1013910398731:ios:f0decf7d06c945a493e40e',
    messagingSenderId: '1013910398731',
    projectId: 'detailing-xperts',
    storageBucket: 'detailing-xperts.appspot.com',
    iosBundleId: 'com.example.responsiveDashboard',
  );
}
